name: hellow-world
on: push
jobs:
  hello-world-job:
    enviroment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  
      - run: echo "$(cat hello_world.txt)"
      - name: Check if variable is accsible
          with:
            credentials: ${{API_KEY_PASS}}
      - run: echo $API_KEY_PASS
    
